ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: $PORT

firebase:
  projectId: $BIFROST_FB_PROJECT_ID
  privateKey: $BIFROST_FB_PRIVATE_KEY
  clientEmail: $BIFROST_FB_CLIENT_EMAIL
