ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: $PORT
    host: 0.0.0.0

firebase:
  projectId: $BIFROST_FB_PROJECT_ID
  privateKey: $BIFROST_FB_PRIVATE_KEY
  clientEmail: $BIFROST_FB_CLIENT_EMAIL
